# Generated by Django 5.2.5 on 2025-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_resource_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('pdf', 'PDF'), ('ppt', 'PPT'), ('doc', 'DOC'), ('docx', 'DOCX'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('zip', 'ZIP'), ('rar', 'RAR'), ('other', 'Other')], default='note', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_category',
            field=models.CharField(choices=[('note', 'Note'), ('question paper', 'Question Paper'), ('presentation', 'Presentation'), ('other', 'Other')], default='image', max_length=255),
        ),
    ]
