# Generated by Django 5.2.5 on 2025-08-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_resource_resource_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_category',
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('note', 'Note'), ('question paper', 'Question Paper'), ('presentation', 'Presentation'), ('other', 'Other')], default='image', max_length=255),
        ),
    ]
