# Generated by Django 5.2.5 on 2025-08-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_alter_subject_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at']},
        ),
    ]
