# Generated by Django 5.2.5 on 2025-08-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_alter_resource_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-name']},
        ),
    ]
