# Generated by Django 5.2.5 on 2025-08-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_alter_subject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
    ]
