# Generated by Django 5.2.5 on 2025-08-30 12:27

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Write your blog content in Markdown format'),
        ),
    ]
